// Global application constants and configuration thresholds

export const COLORS = [
    "Pink",
    "Blue",
    "Green",
    "Yellow",
    "Purple",
    "Orange",
    "Red",
    "Teal",
    "Indigo",
    "Cyan",
    "Lime",
    "Amber",
    "Deep-Purple",
    "Light-Blue",
    "Silver",
    "Gold",
];

export const ANIMALS = [
    "Giraffe",
    "Hippo",
    "Zebra",
    "Lion",
    "Tiger",
    "Elephant",
    "Penguin",
    "Koala",
    "Panda",
    "Fox",
    "Wolf",
    "Bear",
    "Eagle",
    "Owl",
    "Shark",
    "Dolphin",
    "Whale",
    "Octopus",
];

export const ACADEMY_BRANCHES = [
    "Actors",
    "Animation",
    "Artist Representatives",
    "Casting Directors",
    "Cinematographers",
    "Costume Designers",
    "Directors",
    "Documentary",
    "Executives",
    "Film Editors",
    "Makeup Artists and Hairstylists",
    "Marketing and Public Relations",
    "Music",
    "Producers",
    "Production and Technology",
    "Production Design",
    "Short Films",
    "Sound",
    "Visual Effects",
    "Writers",
    "Members-at-Large",
    "Associates",
];

export const ADMIN_EMAIL = "rob.bredow@gmail.com";
export const FADE_TIME = 5000; // 5 seconds
export const INITIAL_SHOW_TIME = 8000; // 8 seconds on launch

// Mobile and touch graph thresholds
export const MOBILE_FAN_THRESHOLD = 32;
export const MOBILE_DRAG_THRESHOLD = 12;
export const MOBILE_MIN_ZOOM = 1;
export const MOBILE_MAX_ZOOM = 3.5;
export const MOBILE_PLOT_TOP_INSET = 60;
export const MOBILE_PLOT_BOTTOM_INSET = 32;
export const MOBILE_TIMELINE_PLOT_BOTTOM_INSET = 78;

// Initial data seed for tools
export const initialItems = [
    {
        id: "d01",
        name: "Denoising",
        x: 4,
        y: 98,
        desc: "Mathematical pixel cleanup. Standard in every render engine.",
        tags: ["Visual Effects", "Production and Technology"],
    },
    {
        id: "d02",
        name: "Script Breakdown",
        x: 10,
        y: 96,
        desc: "Scans text to tag props, cast, & scenes automatically.",
        tags: ["Writers", "Directors", "Producers"],
    },
    {
        id: "d03",
        name: "Upscaling",
        x: 16,
        y: 94,
        desc: "Topaz/Nvidia. Essential for remastering archival footage.",
        tags: ["Visual Effects", "Film Editors"],
    },
    {
        id: "d04",
        name: "Audio Separation",
        x: 22,
        y: 92,
        desc: "Splitting vocals from music (stems). Industry standard.",
        tags: ["Sound", "Music"],
    },
    {
        id: "d05",
        name: "Rotoscoping",
        x: 28,
        y: 90,
        desc: "Magic Mask. Automating cutouts. 90% perfect, 10% manual fix.",
        tags: ["Visual Effects", "Animation"],
    },
    {
        id: "d06",
        name: "Auto-Captions",
        x: 34,
        y: 95,
        desc: "Speech-to-text. Integrated into Premiere/DaVinci.",
        tags: ["Film Editors", "Sound"],
    },
    {
        id: "d07",
        name: "Automated ADR",
        x: 40,
        y: 86,
        desc: "AI dialogue replacement / syncing. Clean but lacks nuances.",
        tags: ["Sound", "Actors"],
    },
    {
        id: "d08",
        name: "Speech Enhancement",
        x: 46,
        y: 84,
        desc: "Adobe Voice Enhance. Strips reverb and mic bleed completely.",
        tags: ["Sound", "Film Editors"],
    },
    {
        id: "d09",
        name: "Neural Radiance (NeRF)",
        x: 52,
        y: 78,
        desc: "Turn 2D photos into a 3D volume. Fast set scanning.",
        tags: ["Visual Effects", "Production Design", "Cinematographers"],
    },
    {
        id: "d10",
        name: "Voice Cloning",
        x: 58,
        y: 72,
        desc: "ElevenLabs. Fast temp track generation; uncanny in final master.",
        tags: ["Actors", "Sound"],
    },
    {
        id: "d11",
        name: "Text-to-SFX",
        x: 64,
        y: 65,
        desc: "Instant sound effects generation. Decent for ambient noise.",
        tags: ["Sound"],
    },
    {
        id: "d12",
        name: "AI Depth Maps",
        x: 70,
        y: 60,
        desc: "Z-depth extraction from 2D. Great for depth of field / lighting.",
        tags: ["Visual Effects", "Cinematographers"],
    },
    {
        id: "d13",
        name: "Storyboard Gen",
        x: 76,
        y: 52,
        desc: "Midjourney/Ideogram for pitch decks. Inconsistent characters.",
        tags: ["Directors", "Production Design", "Writers"],
    },
    {
        id: "d14",
        name: "Generative Fill Video",
        x: 82,
        y: 45,
        desc: "Object removal & video patching. Struggles with fast motion.",
        tags: ["Visual Effects"],
    },
    {
        id: "d15",
        name: "Motion Capture Video",
        x: 88,
        y: 38,
        desc: "Markerless mocap from single phone video (Wonder Dynamics).",
        tags: ["Animation", "Visual Effects"],
    },
    {
        id: "d16",
        name: "Text-to-Music",
        x: 92,
        y: 30,
        desc: "Suno/Udio. Catchy temp cues, hard to orchestrate or stem out.",
        tags: ["Music"],
    },
    {
        id: "d17",
        name: "Video Gen (B-Roll)",
        x: 95,
        y: 22,
        desc: "Runway/Luma/Kling. Amazing 4s clips, hard to direct continuity.",
        tags: ["Cinematographers", "Directors"],
    },
    {
        id: "d18",
        name: "Character In-Betweening",
        x: 98,
        y: 15,
        desc: "Automated 2D anime frame interpolation. Struggles with turns.",
        tags: ["Animation"],
    },
    {
        id: "d19",
        name: "Idea to Script (Long)",
        x: 99,
        y: 8,
        desc: "LLMs generating 90-page feature scripts. Lacks soul / pacing.",
        tags: ["Writers"],
    },
    {
        id: "d20",
        name: "Face Relighting",
        x: 62,
        y: 58,
        desc: "Post-production lighting changes on actor faces via neural normal maps.",
        tags: ["Visual Effects", "Cinematographers"],
    },
    {
        id: "d21",
        name: "Lip Sync Dubbing",
        x: 74,
        y: 48,
        desc: "Multi-language visual dubbing (Flawless AI / HeyGen).",
        tags: ["Actors", "Sound", "Directors"],
    },
    {
        id: "d22",
        name: "Virtual Production Backgrounds",
        x: 85,
        y: 42,
        desc: "AI-assisted real-time LED wall background rendering & parallax.",
        tags: ["Cinematographers", "Production Design", "Visual Effects"],
    },
    {
        id: "d23",
        name: "AI Color Grading",
        x: 38,
        y: 75,
        desc: "Shot matching and palette emulation across camera formats.",
        tags: ["Film Editors", "Cinematographers"],
    },
    {
        id: "d24",
        name: "Synthetic Extra / Crowd Gen",
        x: 80,
        y: 35,
        desc: "Populating background stadiums & streets with AI-driven digital humans.",
        tags: ["Visual Effects", "Casting Directors"],
    },
    {
        id: "d25",
        name: "AI De-Aging",
        x: 68,
        y: 68,
        desc: "Neural face modification for actor age transitions (Metaphysic / Disney).",
        tags: ["Visual Effects", "Makeup Artists and Hairstylists", "Actors"],
    },
    {
        id: "d26",
        name: "Automated B-Roll Tagging",
        x: 18,
        y: 88,
        desc: "Vision AI auto-tagging footage by action, emotion, and shot type.",
        tags: ["Film Editors", "Documentary"],
    },
    {
        id: "d27",
        name: "Costume Concepting",
        x: 78,
        y: 55,
        desc: "Rapid generative iteration on period and fantasy wardrobe designs.",
        tags: ["Costume Designers"],
    },
    {
        id: "d28",
        name: "3D Asset Generation",
        x: 84,
        y: 28,
        desc: "Text/image to textured 3D mesh (Tripo, Meshy, CSM). Low topology quality.",
        tags: ["Visual Effects", "Animation", "Production Design"],
    },
    {
        id: "d29",
        name: "AI Continuity Tracking",
        x: 25,
        y: 62,
        desc: "Script supervisor assistant detecting prop/wardrobe mismatches across takes.",
        tags: ["Directors", "Producers", "Costume Designers"],
    },
    {
        id: "d30",
        name: "Marketing Cutdowns",
        x: 48,
        y: 70,
        desc: "Auto-generating social clips, aspect ratio re-framing, and teasers.",
        tags: ["Marketing and Public Relations", "Film Editors"],
    },
    {
        id: "d31",
        name: "Trailer Generation",
        x: 86,
        y: 20,
        desc: "Automated narrative trailer cutting with AI beat-matching and pacing.",
        tags: ["Marketing and Public Relations", "Film Editors", "Producers"],
    },
    {
        id: "d32",
        name: "Audio Mastering AI",
        x: 30,
        y: 82,
        desc: "Automated loudness matching, EQ balance, and stem mastering.",
        tags: ["Sound", "Music"],
    },
];
